data<-featureCounts(c(
"/home/roberto/deepa/tam_wai_leong/bam/P019WKF_normal_Aligned.sortedByCoord.out.bam",
"/home/roberto/deepa/tam_wai_leong/bam/P1446_normal_Aligned.sortedByCoord.out.bam",
"/home/roberto/deepa/tam_wai_leong/bam/P019WKF_tumor_Aligned.sortedByCoord.out.bam",
"/home/roberto/deepa/tam_wai_leong/bam/P1446_tumor_Aligned.sortedByCoord.out.bam",
"/home/roberto/deepa/tam_wai_leong/bam/P1456_tumor_Aligned.sortedByCoord.out.bam",
"/home/roberto/deepa/tam_wai_leong/bam/P1463_tumor_Aligned.sortedByCoord.out.bam",
"/home/roberto/deepa/tam_wai_leong/bam/P360_tumor_Aligned.sortedByCoord.out.bam",
"/home/roberto/deepa/tam_wai_leong/bam/P520_tumor_Aligned.sortedByCoord.out.bam"
),
annot.ext="/home/roberto/references/gencode.v26.annotation.gtf",
isGTFAnnotationFile=TRUE,
minMQS=10,
strandSpecific=0,
isPairedEnd=TRUE,
#PE_orientation="rf",
autosort=TRUE,
nthreads=15,
GTF.attrType="gene_name"
)
